// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BackEndApi.Models;

public partial class Butaca
{
    public int IdButaca { get; set; }

    public int NroButaca { get; set; }

    public int NroSala { get; set; }

    public int IdTipoButaca { get; set; }

    public bool Disponible { get; set; }

    public virtual TiposButaca IdTipoButacaNavigation { get; set; }

    public virtual Sala NroSalaNavigation { get; set; }

    public virtual ICollection<Ticket> Tickets { get; set; } = new List<Ticket>();
}