// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BackEndApi.Models;

public partial class DetalleFactura
{
    public int IdDetalleFactura { get; set; }

    public int? NroFuncion { get; set; }

    public int? NroFactura { get; set; }

    public int? CodPromocion { get; set; }

    public virtual Promocione CodPromocionNavigation { get; set; }

    public virtual Factura NroFacturaNavigation { get; set; }

    public virtual Funcione NroFuncionNavigation { get; set; }
}