// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BackEndApi.Models;

public partial class FormatoPelicula
{
    public int IdFormato { get; set; }

    public string TipoFormato { get; set; }

    public virtual ICollection<Funcione> Funciones { get; set; } = new List<Funcione>();
}