// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BackEndApi.Models;

public partial class Funcione
{
    public int NroFuncion { get; set; }

    public DateTime? Dia { get; set; }

    public DateTime? Hora { get; set; }

    public int? IdPelicula { get; set; }

    public int? NroSala { get; set; }

    public int? IdFormato { get; set; }

    public int? IdIdioma { get; set; }

    public virtual ICollection<DetalleFactura> DetalleFacturas { get; set; } = new List<DetalleFactura>();

    public virtual FormatoPelicula IdFormatoNavigation { get; set; }

    public virtual Idioma IdIdiomaNavigation { get; set; }

    public virtual Pelicula IdPeliculaNavigation { get; set; }

    public virtual Sala NroSalaNavigation { get; set; }

    public virtual ICollection<Reserva> Reservas { get; set; } = new List<Reserva>();

    public virtual ICollection<Ticket> Tickets { get; set; } = new List<Ticket>();
}