// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BackEndApi.Models;

public partial class Pelicula
{
    public int IdPelicula { get; set; }

    public string Titulo { get; set; }

    public int? IdGenero { get; set; }

    public int? IdEdad { get; set; }

    public short? Duracion { get; set; }

    public string Descripcion { get; set; }

    public int? IdDirector { get; set; }

    public bool? Estreno { get; set; }

    public string Url { get; set; }

    public virtual ICollection<Funcione> Funciones { get; set; } = new List<Funcione>();

    public virtual Directore IdDirectorNavigation { get; set; }

    public virtual Edade IdEdadNavigation { get; set; }

    public virtual GenerosPeli IdGeneroNavigation { get; set; }

    public virtual ICollection<Actore> IdActors { get; set; } = new List<Actore>();
}