// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BackEndApi.Models;

public partial class Sala
{
    public int NroSala { get; set; }

    public int Capacidad { get; set; }

    public int IdTipoSala { get; set; }

    public int IdSucursal { get; set; }

    public virtual ICollection<Butaca> Butacas { get; set; } = new List<Butaca>();

    public virtual ICollection<Funcione> Funciones { get; set; } = new List<Funcione>();

    public virtual Sucursale IdSucursalNavigation { get; set; }

    public virtual TipoSala IdTipoSalaNavigation { get; set; }
}