// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BackEndApi.Models;

public partial class Sucursale
{
    public int IdSucursal { get; set; }

    public int IdBarrio { get; set; }

    public string NombreSucursal { get; set; }

    public virtual Barrio IdBarrioNavigation { get; set; }

    public virtual ICollection<Sala> Salas { get; set; } = new List<Sala>();
}