// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BackEndApi.Models;

public partial class Ticket
{
    public int NroTicket { get; set; }

    public int NroFuncion { get; set; }

    public int IdButaca { get; set; }

    public virtual Butaca IdButacaNavigation { get; set; }

    public virtual Funcione NroFuncionNavigation { get; set; }
}